dist: xenial
language: java
jdk:
  - openjdk8
addons:
  apt:
    packages:
      - junit4
      - ant
      - ant-optional
script: ant
notifications:
  email:
    recipients:
      - hridesh@iastate.edu
      - sayem@iastate.edu
      - sumon@iastate.edu
    on_success: change
    on_failure: always
